// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20220618092425_DummyDataadded")]
    partial class DummyDataadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The one with big park",
                            Name = "New york"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The one with SidiSaiyad-Jali",
                            Name = "Ahmedabad"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The one which is my home town",
                            Name = "Rajkot"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Most Visited Central",
                            Name = "Central park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Most Visited Empire",
                            Name = "Empire park"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Most Visited Sidi-Saiyad",
                            Name = "Sidi-Saiyad jali"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Most Visited Corporate",
                            Name = "Corporate road"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Most Visited Race course",
                            Name = "Race course"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "Most Visited Trikon baug",
                            Name = "Trikon baug"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
